# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Nyasha Ndhlovu
# Description of the Site
description: A journey into the DevOps Space and Time
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://nyashandhlovu.co.za/wp-content/uploads/2022/06/logo-22.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.unsplash.com/photo-1563656157432-67560011e209?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1632&q=80

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: nynyashadzashe@gmail.com
facebook_username: optimusny
twitter_username: optimusny
instagram_username: optimusny
linkedin_username: /nyashadzashe-ndhlovu/
github_username:  nyashad

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Nyasha Ndhlovu

# Name of the Author
author-name: Nyasha Ndhlovu
# URL for the Image of the Author
author-image: https://nyashandhlovu.co.za/wp-content/uploads/2022/08/pp.jpg
# 60 Words About the Author
author-about: With a demonstrated history of working in the telecommunications industry. I have expert knowledge of EC2, VPC, AWS Cloudwatch, Messaging & Containers, Route53, VPNs, AutoScaling, Infrastructure as Code, LoadBalancing and Web Application Firewalls, Elastic beanstalk, Cloudformation, Code Pipeline, CICD, Kubernetes, CircleCI, Prometheus
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/nyashad

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
